"""Initial migration

Revision ID: 595b05e33e13
Revises: 
Create Date: 2024-11-10 15:04:29.471351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '595b05e33e13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if 'users' table exists before creating it
    op.execute('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER NOT NULL AUTO_INCREMENT, 
            name VARCHAR(50), 
            PRIMARY KEY (id)
        );
    ''')

    # Drop other tables if they exist
    op.execute('DROP TABLE IF EXISTS Tables;')
    op.execute('DROP TABLE IF EXISTS Kitchen;')
    op.execute('DROP TABLE IF EXISTS Orders;')
    op.execute('DROP TABLE IF EXISTS Reservation;')
    op.execute('DROP TABLE IF EXISTS menu_item;')
    op.execute('DROP TABLE IF EXISTS Items;')
    op.execute('DROP TABLE IF EXISTS Customer;')
    op.execute('DROP TABLE IF EXISTS Feedback;')

    # Create the 'users' table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
    sa.Column('cust_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cust_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cust_mail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cust_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('cust_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Items',
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('item_rating', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('menu_item',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Reservation',
    sa.Column('reservation_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.TIME(), nullable=True),
    sa.Column('no_of_people', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cust_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['Customer.cust_id'], name='reservation_ibfk_2'),
    sa.ForeignKeyConstraint(['table_id'], ['Tables.table_id'], name='reservation_ibfk_1'),
    sa.PrimaryKeyConstraint('reservation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Orders',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_time', mysql.TIME(), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('cust_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['Customer.cust_id'], name='orders_ibfk_1'),
    sa.ForeignKeyConstraint(['item_id'], ['Items.item_id'], name='orders_ibfk_2'),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.staff_id'], name='orders_ibfk_3'),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Kitchen',
    sa.Column('kitchen_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Items.item_id'], name='kitchen_ibfk_2'),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], name='kitchen_ibfk_3'),
    sa.ForeignKeyConstraint(['staff_id'], ['Staff.staff_id'], name='kitchen_ibfk_1'),
    sa.PrimaryKeyConstraint('kitchen_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Tables',
    sa.Column('table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_people', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('table_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Staff',
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('staff_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('staff_phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('staff_type', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('staff_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Feedback',
    sa.Column('feedback_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_rating', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('cust_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['Customer.cust_id'], name='feedback_ibfk_1'),
    sa.PrimaryKeyConstraint('feedback_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('users')
    # ### end Alembic commands ###
